[package]
name = "bounce"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
desktop = ["wgame/desktop"]
web = ["wgame/web"]

[dependencies]
derive_more = { version = "2.1.1", features = ["deref", "deref_mut"] }
glam = { version = "0.33.7", features = ["rand"] }
hsl = "0.1.1"
phy = { path = "phy" }
geom2 = { path = "geom2" }
rand = { version = "0.10.2", default-features = false, features = ["std"] }
rand_distr = "0.6.0"
rgb = "0.8.53"
wgame = { path = "wgame/wgame", default-features = false, features = [
    "shapes",
    "image",
    "typography",
] }
